from constants import WebsiteUrls as website_urls
from scraper_configs import *

WebsiteSettings = [
    # culture kings
    {
        'id': '211',
        'website_id': 2,
        'gender': 1,
        'category': 1,
        'base_url': website_urls.culture_kings,
        'url': website_urls.culture_kings + '/collections/mens-tops?page=',
        'scraper_config': culture_kings_config,
    },
    {
        'id': '212',
        'website_id': 2,
        'gender': 1,
        'category': 2,
        'base_url': website_urls.culture_kings,
        'url': website_urls.culture_kings + '/collections/mens-bottoms?page=',
        'scraper_config': culture_kings_config,
    },
    {
        'id': '221',
        'website_id': 2,
        'gender': 2,
        'category': 1,
        'base_url': website_urls.culture_kings,
        'url': website_urls.culture_kings + '/collections/womens-tops?page="',
        'scraper_config': culture_kings_config,
    },
    {
        'id': '222',
        'website_id': 2,
        'gender': 2,
        'category': 2,
        'base_url': website_urls.culture_kings,
        'url': website_urls.culture_kings + '/collections/womens-bottoms?page=',
        'scraper_config': culture_kings_config,
    },
    # the iconic
    {
        'id': '311',
        'website_id': 3,
        'gender': 1,
        'category': 1,
        'base_url': website_urls.the_iconic,
        'url': website_urls.the_iconic + '/mens-clothing-tshirts-singlets/?page=',
        'scraper_config': the_iconic_config,
    },
    {
        'id': '312',
        'website_id': 3,
        'gender': 1,
        'category': 2,
        'base_url': website_urls.the_iconic,
        'url': website_urls.the_iconic + '/mens-clothing-pants/?page=',
        'scraper_config': the_iconic_config,
    },
    {
        'id': '321',
        'website_id': 3,
        'gender': 2,
        'category': 1,
        'base_url': website_urls.the_iconic,
        'url': website_urls.the_iconic + '/womens-clothing-tops/?page=',
        'scraper_config': the_iconic_config,
    },
    {
        'id': '322',
        'website_id': 3,
        'gender': 2,
        'category': 2,
        'base_url': website_urls.the_iconic,
        'url': website_urls.the_iconic + '/womens-clothing-pants/?page=',
        'scraper_config': the_iconic_config,
    },
    # Peppermayo
    {
        'id': '411',
        'website_id': 4,
        'gender': 1,
        'category': 1,
        'base_url': website_urls.pepper_mayo,
        'url': website_urls.pepper_mayo + '/men/clothing/tops/shirts?p=',
        'scraper_config': pepper_mayo_config,
    },
    {
        'id': '412',
        'website_id': 4,
        'gender': 1,
        'category': 2,
        'base_url': website_urls.pepper_mayo,
        'url': website_urls.pepper_mayo + '/men/clothing/jeans-chino?p=',
        'scraper_config': pepper_mayo_config,
    },
    {
        'id': '421',
        'website_id': 4,
        'gender': 2,
        'category': 1,
        'base_url': website_urls.pepper_mayo,
        'url': website_urls.pepper_mayo + '/women/clothing/tops?p=',
        'scraper_config': pepper_mayo_config,
    },
    {
        'id': '422',
        'website_id': 4,
        'gender': 2,
        'category': 2,
        'base_url': website_urls.pepper_mayo,
        'url': website_urls.pepper_mayo + '/women/clothing/jeans?p=',
        'scraper_config': pepper_mayo_config,      
    }
]